<section class="mi-slider">
    <div class="slider home-slider">
        <div class="slider-wrapper">
            <div class="slider-content">
                <div class="slider-img">
                    <img src="https://s3.amazonaws.com/lms-website-img/_Mi-8-Lite_photo_2.png" alt=""></div>
                <div class="slider-text">
                    <h1>
                        Mi Pro Titanium
                        <span class='slider-text--span'>Cameras, all -new AI portraits</span>
                    </h1>
                    <p>5.99" Large Display
                        <br>13MP Selfie Camera
                        <br>3 -Choose-2 NonoSim/MicroSD Slot</p>
                    <a class="btn--slider" href="#">Learn more</a></div>
            </div>
        </div>
        <div class="slider-wrapper">
            <div class="slider-content">
                <div class="slider-img">
                    <img src="https://s3.amazonaws.com/lms-website-img/_redminote5_002.png" alt=""></div>
                <div class="slider-text">
                    <h1>
                        Mi Pro Titanium
                        <span class="slider-text--span">The Camera Beast</span>
                    </h1>
                    <p>5.99" Large Display
                        <br>13MP Selfie Camera
                        <br>3 -Choose-2 NonoSim/MicroSD Slot</p>
                    <a class="btn--slider" href="#">View more</a></div>
            </div>
        </div>
        <div class="slider-wrapper">
            <div class="slider-content">
                <div class="slider-img">
                    <img src="https://s3.amazonaws.com/lms-website-img/_Mi_Mix_3_001.png" alt=""></div>
                <div class="slider-text">
                    <h1>
                        Mi Pro Titanium
                        <span class="slider-text--span">The Camera Beast</span>
                    </h1>
                    <p>5.99" Large Display
                        <br>13MP Selfie Camera
                        <br>3 -Choose-2 NonoSim/MicroSD Slot</p>
                    <a class="btn--slider" href="#">View more</a></div>
            </div>
        </div>
    </div>
</section>
<div class="new-products">
    <h2 class="with-line">New Products</h2>
    <ul>
        <li>
            <a class="product-img" href="/mi-mix-3-6g-128gb-onyx-black">
                <img src="{{media url=&quot;products/mi-mix-3/afo2.png&quot;}}" alt=""></a>
            <a class="product-title" href="/mi-mix-3-6g-128gb-onyx-black">Mi Mix 3</a></li>
        <li>
            <a class="product-img" href="/mi-m365-electric-scooter">
                <img src="{{media url=&quot;products/mi-electric-scooter/scooter-black-1.png&quot;}}" alt=""></a>
            <a class="product-title" href="/mi-m365-electric-scooter">Mi M365 Electric Scooter</a></li>
        <li>
            <a class="product-img" href="/mi-band-3">
                <img src="{{media url=&quot;products/mi-band-3/xiaomi-mi-band-3-1.png&quot;}}" alt=""></a>
            <a class="product-title" href="/mi-band-3">Fitness Tracker Mi Band 3</a></li>
        <li>
            <a class="product-img" href="/mi-laser-projector-150-white">
                <img src="{{media url=&quot;products/mi-laser-projector/000.png&quot;}}" alt=""></a>
            <a class="product-title" href="/mi-laser-projector-150-white">Mi Laser Projector 150"</a></li>
    </ul>
</div>
<div class="categories">
    <ul>
        <li>
            <div class="title">
                <h2>Mi Phones</h2>
                <a href="/mi-phones">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-mi-phones.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Smart Devices</h2>
                <a href="/smart-devices">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-smart-devices.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Fitness</h2>
                <a href="/fitness">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-fitness.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Audio</h2>
                <a href="/audio">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-audio.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Mi Power Bank</h2>
                <a href="/mi-power-bank">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-power-banks.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Lifestyle</h2>
                <a href="/lifestyle">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-lifestyle.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Accessories</h2>
                <a href="/accessories">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-accessories.jpg&quot;}}" alt=""></li>
        <li>
            <div class="title">
                <h2>Valentine Sales</h2>
                <a href="/valentine-sales">Learn more</a></div>
            <img src="{{media url=&quot;home-category/category-valentine-sale.jpg&quot;}}" alt=""></li>
    </ul>
    <div class="see-more-btn">
        <button>See more</button></div>
</div>
<div class="home-news">
	<h2 class="with-line">Mi News</h2>
	<ul>
		<li>
			<a href="#">
				<img src="https://i01.appmifile.com/webfile/globalimg/products/pc/pocophone/section-1.jpg">
				<span class="content-wrapper">
					<span class="title">Mi 8 Lite smartphone Available now</span>
					<span class="text">06 December 2018</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<img src="https://i01.appmifile.com/webfile/globalimg/redmi-note-6-pro/e7t_img_01.jpg">
				<span class="content-wrapper">
					<span class="title">Mi Store grand opening</span>
					<span class="text">06 December 2018</span>
				</span>
			</a>
		</li>
		<li>
			<a href="#">
				<img src="https://i01.appmifile.com/webfile/globalimg/18/1940BF56-54B6-FC03-5B80-355955CA2FC4.jpg">
				<span class="content-wrapper">
					<span class="title">Mi Store grand opening</span>
					<span class="text">06 December 2018</span>
				</span>
			</a>
		</li>
	</ul>
</div>

<div class="home-videos">
    <ul>
        <li>
            <a href="www.youtube.com/embed/8lxhEny1fOg">
            	<span class="keynote">QualityMatters: Amazing Products Every Time</span>
                <img src="{{media url=&quot;videos_thumbnail/QualityMatters.jpg?width=398&amp;height=320&quot;}}" alt="QualityMatters: Amazing Products Every Time" /></a></li>
        <li>
            <a href="www.youtube.com/embed/Zi9kWmgcvv8">
            	<span class="keynote">Mi 8 Pro: Unboxing the New Flagship</span>
                <img src="{{media url=&quot;videos_thumbnail/Mi8Pro.jpg?width=398&amp;height=320&quot;}}" alt="Mi 8 Pro: Unboxing the New Flagship" /></a></li>
        <li>
            <a href="www.youtube.com/embed/73KtKq4TzlY">
            	<span class="keynote">Mi Mix 3: Unboxing</span>
                <img src="{{media url=&quot;videos_thumbnail/MiMix3.jpg?width=398&amp;height=320&quot;}}" alt="Mi Mix 3: Unboxing" /></a></li>
        <li>
            <a href="www.youtube.com/embed/hrjY8JlBGnI">
            	<span class="keynote">MoreThanPhones: A Complete Lifestyle Solution</span>
                <img src="{{media url=&quot;videos_thumbnail/MoreThanPhones.jpg?width=398&amp;height=320&quot;}}" alt="MoreThanPhones: A Complete Lifestyle Solution" /></a></li>
    </ul>
</div>
