<section class="mi-slider">
	<div class="slider home-slider">
		<div class="slider-wrapper">
			<div class="slider-content">
				<div class="slider-img">
					<img src="https://s3.amazonaws.com/lms-website-img/_Mi_Mix_3_001.png">
				</div>
				<div class="slider-text">
					<h1>
						Mi Pro Titanium
						<span>Cameras, all -new AI portraits</span>
					</h1>
					<p>
						5.99" Large Display
						<br>
						13MP Selfie Camera
						<br>
						3 -Choose-2 NonoSim/MicroSD Slot
					</p>
					<a href="#" class="btn--slider">Learn more</a>
				</div>
			</div>
		</div>
		<div class="slider-wrapper">
			<div class="slider-content">
				<div class="slider-img">
					<img src="https://s3.amazonaws.com/lms-website-img/_Mi-8-Lite_photo_2.png">
				</div>
				<div class="slider-text">
					<h1>
						Mi Pro Titanium
						<span>The Camera Beast</span>
					</h1>
					<p>
						5.99" Large Display
						<br>
						13MP Selfie Camera
						<br>
						3 -Choose-2 NonoSim/MicroSD Slot
					</p>
					<a href="#" class="btn--slider">View more</a>
				</div>
			</div>
		</div>
		<div class="slider-wrapper">
			<div class="slider-content">
				<div class="slider-img">
					<img src="https://s3.amazonaws.com/lms-website-img/_redminote5_002.png">
				</div>
				<div class="slider-text">
					<h1>
						Mi Pro Titanium
						<span>The Camera Beast</span>
					</h1>
					<p>
						5.99" Large Display
						<br>
						13MP Selfie Camera
						<br>
						3 -Choose-2 NonoSim/MicroSD Slot
					</p>
					<a href="#" class="btn--slider">View more</a>
				</div>
			</div>
		</div>
	</div>
</section>
