<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<form class="form minisearch"  id="minisearch" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
	<div class="field search">
		<label class="label">
		</label>
		<div class="control">
			<input
				id="search"
				data-mage-init='{"quickSearch":{
					"formSelector":"#minisearch",
					"url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
					"destinationSelector":"#search-autocomplete"}
				}'
				type="text"
				name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
				value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
				placeholder="<?= /* @escapeNotVerified */ __('Search entire store here...') ?>"
				class="input-text"
				maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
				role="combobox"
				aria-haspopup="false"
				aria-autocomplete="both"
				autocomplete="off"
			/>
			<div id="search-autocomplete" class="search-autocomplete"></div>
		</div>
	</div>
	<div class="actions">
		<button
			type="submit"
			title="<?= $block->escapeHtml(__('Search')) ?>"
			class="action search" >
			<span><?= /* @escapeNotVerified */ __('Search') ?></span>
		</button>
	</div>
</form>
