<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
?>
<?php if (!$block->isLoggedIn()):
	$dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
?>
<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
        <?= $block->escapeHtml(__('Login or Register')) ?>
    </a>
</li>
<?php else: ?>
	<?= $block->getChildHtml('my-account-link')?>
	<li class="authorization-link" data-label="<?= $block->escapeHtml(__('or')) ?>">
		<a <?= /* @noEscape */ $block->getLinkAttributes() ?><?= /* @noEscape */ $dataPostParam ?>>
			<?= $block->escapeHtml($block->getLabel()) ?>
		</a>
	</li>
<?php endif;?>
